db:
  image: mongo:3.2
  volumes:
    - ./volumes/db/data:/data/db
    - ./volumes/db/config:/data/configdb
docker:
  build: docker/.
  privileged: true
  volumes:
    - ./volumes/docker:/var/lib/docker
    - ./tmp/containers:/app/containers
hwserver2:
  build: hwserver2/.
  command: rackup
  ports:
    - "2500:2500"
  volumes:
    - ./hwserver2:/app
    - ./log:/app/log
    - ./tmp/containers:/app/containers
  links:
    - db
    - docker
  env_file: .env
apiserver:
  build: apiserver/.
  command: rackup config.ru -s puma
  ports:
    - "2600:2600"
  volumes:
    - ./apiserver:/app
  links:
    - db
  env_file: .env
web:
  build: ./web
  command: ember server
  ports:
    - "4200:4200"
  volumes:
    - ./web/app:/app/app
    - ./web/public:/app/public
    - ./web/tests:/app/tests
    - ./web/config:/app/config
  env_file: .env
mail:
  image: tozd/postfix
  ports:
    - "25:25"
