db:
  image: mongo:3.2
  volumes:
    - mzg_db:/data/db
# web:
#   build: .
#   command: ruby interface/app.rb
#   ports:
#     - "4567:4567"
#   volumes:
#     - .:/app
#   links:
#     - db
#   env_file: .env
control:
  build: .
  command: ruby control/app.rb
  ports:
    - "3900:3900"
  volumes:
    - .:/app
  links:
    - db
  env_file: .env
hwserver:
  build: .
  command: ruby hwserver/server.rb
  ports:
    - "2500:2500"
  volumes:
    - .:/app
  links:
    - db
  env_file: .env
web2:
  build: ./web2
  command: ember server
  ports:
    - "4200:4200"
  volumes:
    - ./web2/app:/app/app
    - ./web2/public:/app/public
    - ./web2/tests:/app/tests
    - ./web2/config:/app/config
  links:
    - db
    - apiserver
    - control
  env_file: .env
apiserver:
  build: apiserver/.
  command: ruby app.rb
  ports:
    - "2600:2600"
  volumes:
    - ./apiserver:/app
  links:
    - db
  env_file: .env
