db:
  image: mongo:3.2
  volumes:
    - mzg_db:/data/db
    - mzg_db_config:/data/configdb
docker:
  build: docker/.
  privileged: true
  ports:
    - "2375:2375"
  volumes:
    - mzg_docker:/var/lib/docker
    - ./containers:/app/containers
control:
  build: control/.
  command: ruby app.rb
  ports:
    - "3900:3900"
  volumes:
    - ./control:/app
    - ./db-code:/app/db-code
  links:
    - db
  env_file: .env
hwserver2:
  build: hwserver2/.
  command: rackup
  ports:
    - "2500:2500"
  volumes:
    - ./hwserver2:/app
    - ./log:/app/log
    - ./db-code:/app/db-code
    - ./containers:/app/containers
  links:
    - db
    - docker
  env_file: .env
apiserver:
  build: apiserver/.
  command: rackup
  ports:
    - "2600:2600"
  volumes:
    - ./apiserver:/app
  links:
    - db
  env_file: .env
web:
  build: ./web
  command: ember server
  ports:
    - "4200:4200"
  volumes:
    - ./web/app:/app/app
    - ./web/public:/app/public
    - ./web/tests:/app/tests
    - ./web/config:/app/config
  env_file: .env
game:
  build: ./game
  command: ember server
  ports:
    - "4340:4340"
  volumes:
    - ./game/app:/app/app
    - ./game/public:/app/public
    - ./game/tests:/app/tests
    - ./game/config:/app/config
  env_file: .env
