db:
  image: mongo:3.2
  volumes:
    - mzg_db:/data/db
web:
  build: .
  command: ruby interface/app.rb
  ports:
    - "4567:4567"
  volumes:
    - .:/app
  links:
    - db
  env_file: .env
aserver:
  build: .
  command: ruby aserver.rb
  ports:
    - "2500:2500"
  volumes:
    - .:/app
  links:
    - db
  env_file: .env
