db:
  image: mongo:3.2
  volumes:
    - mzg_db:/data/db
web:
  build: .
  command: ruby interface/app.rb
  ports:
    - "4567:4567"
  volumes:
    - .:/app
  links:
    - db
  env_file: .env
hwserver:
  build: .
  command: ruby hwserver/server.rb
  ports:
    - "2500:2500"
  volumes:
    - .:/app
  links:
    - db
  env_file: .env
web2:
  build: ./web2
  command: npm start
  ports:
    - "4200:4200"
  volumes:
    - ./web2/:/app
    - /app/node_modules/
    - /app/bower_components/
    - /app/async-disk-cache/
    - /app/tmp/
    - /app/dist/
  links:
    - db
  env_file: .env
apiserver:
  build: .
  command: ruby app.rb
  ports:
    - "2600:2600"
  volumes:
    - ./apiserver:/app
  links:
    - db
  env_file: .env
