db:
  image: mongo:3.2
  restart: always
  volumes:
    - ./volumes/db/data:/data/db
    - ./volumes/db/config:/data/configdb
docker:
  build: docker/.
  restart: always
  privileged: true
  volumes:
    - ./volumes/docker:/var/lib/docker
    - ./tmp/containers:/app/containers
hwserver2:
  restart: always
  build: hwserver2/.
  command: rackup
  ports:
    - "2500:2500"
  volumes:
    - ./hwserver2:/app
    - ./log:/app/log
    - ./tmp/containers:/app/containers
  links:
    - db
    - docker
  env_file: .env.production
apiserver:
  restart: always
  build: apiserver/.
  command: rackup config.ru -s puma -E production
  ports:
    - "2600:2600"
  volumes:
    - ./apiserver:/app
  links:
    - db
    - mail
  env_file: .env.production
web:
  build: web/.
  command: ember build --environment=production
  volumes:
    - ./web/dist:/app/dist
mail:
  restart: always
  image: tozd/postfix
