db:
  image: mongo:3.2
  volumes:
    - mzg_db:/data/db
control:
  build: .
  command: ruby control/app.rb
  ports:
    - "3900:3900"
  volumes:
    - .:/app
  links:
    - db
  env_file: .env
hwserver:
  build: .
  command: ruby hwserver3/server.rb
  ports:
    - "2500:2500"
  volumes:
    - .:/app
  links:
    - db
  env_file: .env
apiserver:
  build: apiserver/.
  command: ruby app.rb
  ports:
    - "2600:2600"
  volumes:
    - ./apiserver:/app
  links:
    - db
  env_file: .env
web:
  build: ./web
  command: ember server
  ports:
    - "4200:4200"
  volumes:
    - ./web/app:/app/app
    - ./web/public:/app/public
    - ./web/tests:/app/tests
    - ./web/config:/app/config
  links:
    - db
    - apiserver
    - control
    - hwserver
  env_file: .env
