db:
  image: mongo:3.2
  volumes:
    - ./volumes/db/data:/data/db
    - ./volumes/db/config:/data/configdb
docker:
  build: docker/.
  privileged: true
  volumes:
    - ./volumes/docker:/var/lib/docker
    - ./tmp/containers:/app/containers
apiserver:
  build: apiserver/.
  command: rackup config.ru -s puma
  ports:
    - "2600:2600"
  volumes:
    - ./apiserver:/app
  links:
    - db
  env_file: .env
