source "https://rubygems.org"

gem 'sinatra', '~> 1.4.7'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin', '~> 0.3.2'
gem 'mongo', '~> 2.2.2'

gem 'bcrypt-ruby', '3.1.5'
gem 'warden'
gem 'omniauth-vkontakte', '~> 1.3.6'
gem 'omniauth-google-oauth2'

gem 'byebug'
