source "https://rubygems.org"

gem 'sinatra', '~> 1.4.7'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin', '~> 0.3.2'
gem 'mongoid', '~> 5.1.0'

gem 'bcrypt-ruby', '3.1.5'
gem 'warden', '~> 1.2.6'
gem 'omniauth-vkontakte', '~> 1.3.6'
gem 'omniauth-github', '~> 1.1.2'
gem 'omniauth-google-oauth2'
gem 'mail', '~> 2.6.4'

group :test do
  gem 'database_cleaner'
  gem 'rspec', '~> 3.4.0'
  gem 'factory_girl', '~> 4.7.0', :require => false
end

gem 'byebug'
