source "https://rubygems.org"

gem 'sinatra', '~> 1.4.7'
gem 'mongo', '~> 2.2.2'
gem 'docker-api', '~> 1.28'
gem 'rb-inotify', '~> 0.9.7'
gem 'faye-websocket', '~> 0.10.3'
gem 'puma', '~> 3.4.0'

# Development
gem 'byebug'
