source "https://rubygems.org"

gem 'sinatra', '~> 1.4.7'
gem 'sinatra-websocket', '~> 0.3.1'
gem 'mongo', '~> 2.2.2'
gem 'docker-api', '~> 1.28'
gem 'rb-inotify', '~> 0.9.7'

# Development
gem 'byebug'
